# Generated by Django 3.0.5 on 2020-06-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingPlaces',
            fields=[
                ('Name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Area', models.CharField(max_length=40)),
                ('TotalBlocks', models.IntegerField()),
                ('AvailableBlocks', models.IntegerField()),
                ('PricePerHr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('Bid', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('parkplace', models.CharField(max_length=40)),
                ('area', models.CharField(max_length=40)),
                ('created_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('No_of_hrs', models.IntegerField()),
                ('Total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VhNo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phone', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
