# Generated by Django 3.0.5 on 2020-06-24 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20200624_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingplaces',
            old_name='parkplace',
            new_name='Name',
        ),
    ]
